"""add_multilingual_location_fields

Revision ID: 5740e92ed70c
Revises: 002
Create Date: 2025-11-12 19:19:44.970283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5740e92ed70c'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'is_sender',
               existing_type=sa.BOOLEAN(),
               comment='1=فرستنده کالا, 0=مسافر',
               existing_nullable=False)
    op.add_column('city', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('city', sa.Column('name_fa', sa.String(length=100), nullable=False))
    op.add_column('city', sa.Column('name_ar', sa.String(length=100), nullable=False))
    op.add_column('city', sa.Column('airport_code', sa.String(length=3), nullable=True, comment='IATA airport code'))
    op.create_index(op.f('ix_city_airport_code'), 'city', ['airport_code'], unique=False)
    op.create_index('ix_city_country_name_ar', 'city', ['country_id', 'name_ar'], unique=False)
    op.create_index('ix_city_country_name_en', 'city', ['country_id', 'name_en'], unique=False)
    op.create_index('ix_city_country_name_fa', 'city', ['country_id', 'name_fa'], unique=False)
    op.add_column('country', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('country', sa.Column('name_fa', sa.String(length=100), nullable=False))
    op.add_column('country', sa.Column('name_ar', sa.String(length=100), nullable=False))
    op.add_column('country', sa.Column('iso_code', sa.String(length=3), nullable=True))
    op.drop_constraint('country_name_key', 'country', type_='unique')
    op.create_index(op.f('ix_country_name_ar'), 'country', ['name_ar'], unique=False)
    op.create_index('ix_country_name_en', 'country', ['name_en'], unique=False)
    op.create_index(op.f('ix_country_name_fa'), 'country', ['name_fa'], unique=False)
    op.create_unique_constraint(None, 'country', ['iso_code'])
    op.alter_column('log', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='نوع رویداد: signup, login, join_request, card_create, message_send, ban, unban',
               existing_nullable=False)
    op.drop_index('ix_user_email_verified', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_email_verified', 'user', ['email_verified'], unique=False)
    op.alter_column('log', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='نوع رویداد: signup, login, join_request, card_create, message_send, ban, unban',
               existing_nullable=False)
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_index(op.f('ix_country_name_fa'), table_name='country')
    op.drop_index('ix_country_name_en', table_name='country')
    op.drop_index(op.f('ix_country_name_ar'), table_name='country')
    op.create_unique_constraint('country_name_key', 'country', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('country', 'iso_code')
    op.drop_column('country', 'name_ar')
    op.drop_column('country', 'name_fa')
    op.drop_column('country', 'name_en')
    op.drop_index('ix_city_country_name_fa', table_name='city')
    op.drop_index('ix_city_country_name_en', table_name='city')
    op.drop_index('ix_city_country_name_ar', table_name='city')
    op.drop_index(op.f('ix_city_airport_code'), table_name='city')
    op.drop_column('city', 'airport_code')
    op.drop_column('city', 'name_ar')
    op.drop_column('city', 'name_fa')
    op.drop_column('city', 'name_en')
    op.alter_column('card', 'is_sender',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='1=فرستنده کالا, 0=مسافر',
               existing_nullable=False)
    # ### end Alembic commands ###

